server:  
  port: ${scheduler.server.port:9996}

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: ${scheduler.config.url.eureka:http://discovery-service:8761/eureka/}
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  datasource:
    url: ${scheduler.db.url:jdbc:mysql://10.26.32.14:3306/hrss_scheduler_db?verifyServerCertificate=false&useSSL=true&autoReconnect=true}
    username: ${scheduler.db.username:hrssuser}
    password: ${scheduler.db.password:hrssuser}
    driverClassName: ${scheduler.db.driver:com.mysql.jdbc.Driver}
    
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    baseUrl: ${scheduler.config.url.zipkin:http://zipkin-service:9411}
    
endpoints:
  sensitive: true

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([${springAppName:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
  level:
    org.springframework: WARN
    org.hibernate: WARN
      
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
      
ribbon:
  ConnectTimeout: 30000
  ReadTimeout: 30000
  eureka:
    enabled: true
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0